# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define :default do |config|
    config.vm.box = "CentOS-6.4-java-x86_64"
#    config.vm.synced_folder "~/.m2", "/tmp/.m2"
#	config.vm.synced_folder "#{File.absolute_path('.')}/target/classes", "/tmp/target/classes"
#	config.vm.synced_folder "#{File.absolute_path('.')}/target/test-classes", "/tmp/target/test-classes"
    config.vm.network :private_network, ip: "192.168.56.200"

#    config.vm.provision :chef_solo do |chef|
#      chef.cookbooks_path = "../cookbooks"
#      chef.add_recipe "java"
  
      # You may also specify custom JSON attributes:
#      chef.json = {
#        :java => {
#          :install_flavor => "oracle",
#          :jdk => {
#            '6' => {
#              :i586 => {
#                :url => 'http://192.168.56.1/java/jdk-6u41-linux-i586.bin',
#                :checksum => 'F689675399F3409B883F2E5D458D0819EFFAE9FE3A61A98BFC4AF40E724E8517'
#              },
#              :x86_64 => {
#                :url => 'http://192.168.56.1/java/jdk-6u41-linux-x64.bin',
#                :checksum => 'C87AE51533EFA3D41A2C4086D8BF1F6887E2BD7D0B1BEADBA667D64F89D55598'
#              }
#            }
#          }
#        },
#      }
#    end
  end
end
