#!/usr/bin/env bash

expect -c "
	spawn su root
	expect \"*?assword*\"
	send \"vagrant\r\"
	expect \"#\"
	send \"wget http://download.redis.io/releases/redis-3.0.5.tar.gz\r\"
	expect \"#\"
	send \"tar xzf redis-3.0.5.tar.gz\r\"
	expect \"#\"
	send \"cd redis-3.0.5\r\"
	expect \"#\"
	send \"make\"
	expect \"#\"
	send \"make install\r\"
	expect \"#\"
	send \"cd utils\r\"
	expect \"#\"
	send \"chmod +x install_server.sh\r\"
	expect \"#\"
	send \"./install_server.sh\r\"
	expect -re \".*6379.*\"
    send \"\n\"
    expect -re \".*conf.*\"
    send \"\n\"
    expect -re \".*log.*\"
    send \"\n\"
    expect -re \".*6379\"
    send \"\n\"
    expect -re \".*server.*\"
    send \"\n\"
    expect -re \".*abort.*\"
    send \"\n\"
    expect -re \".*successful.*\"
"