---
- name: Add Java oracle repository into source list
  apt_repository: repo='ppa:webupd8team/java' update_cache=yes
  
- name: Accept License
  debconf: name='oracle-java8-insteller' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
  
#- name: Accept License
#  debconf: name='oracle-java8-insteller' question='shared/accepted-oracle-license-v1-1' value='true' vtype='seen'
  
- name: Install oracle Java8
  apt: name=oracle-java8-installer state=latest  
  
- name: Install additional packages 
  apt: name={{item}}
  with_items:
    - maven
    - ant