# -*- mode: ruby -*-
# vi: set ft=ruby :


$script = <<SCRIPT

apt-get -q -y update
apt-get -q -y install emacs

SCRIPT


Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "dev-ubuntu-12.04"

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  config.vm.provision :shell, :inline => $script

  config.vm.provision :shell, :path => "bootstrap.sh"

  # cloned from https://github.com/opscode-cookbooks/java
  # modified ./cookbooks/java/attributes/default.rb... set default['java']['jdk_version'] = '7'
  config.vm.provision :chef_solo do |chef|
    chef.add_recipe "java"
  end

  config.vm.provision :chef_solo do |chef|
    chef.add_recipe "mysql::server"
    chef.json = { "mysql" => {
                     "server_root_password" => "root",
                     "server_repl_password" => "root",
                     "server_debian_password" => "root"
                   },
                   "run_list" => ["recipe[mysql::server]"]
                 }
  end

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine
  config.vm.network :forwarded_port, guest: 3306, host: 3306
  config.vm.network :forwarded_port, guest: 8843, host: 8843


  config.ssh.forward_x11 = "false"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network :private_network, ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network :public_network

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
 config.vm.provider :virtualbox do |vb|
   # Don't boot with headless mode
   vb.gui = false

   # Use VBoxManage to customize the VM. For example to change memory:
   vb.customize ["modifyvm", :id, "--memory", "1024"]
 end

end

